version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8081:80
        volumes:
            #- "${PROJECT_ROOT}:/var/www/html:ro"
             - "/projects/test:/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - app-network
        environment:
            #MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_ROOT_PASSWORD: 12345
networks:
    app-network:

